def bubble_sort(list_sort): #O(n^2)
    for index_Ext in range(0,len(list_sort)-1): #O(n)
        is_not_changed = True #O(1)
        for index in range(0,len(list_sort)-1-index_Ext): #O(n^2)
            current_item = list_sort[index] #O(1)
            next_item = list_sort[index+1] #O(1)
            if current_item > next_item: #O(1)
                list_sort[index] = next_item #O(1)
                list_sort[index+1] = current_item #O(1)
                is_not_changed = False #O(1)
            print(f"{index_Ext}-{index}={list_sort}") #O(1)
        if is_not_changed: #O(1)
            break #O(1)           

test_list = [9,8,7,6,5,4,3,2,1] #O(1)
print(test_list) #O(1)
bubble_sort(test_list) #O(n^2)
print(test_list) #O(1)

#Resultado: Algoritmo O(n^2)